---
- name: Provision OpenSSH servers on multiple Vagrant machines
  hosts: all
  become: true

  vars:
    openssl_ver: "3.6.0"

  pre_tasks:
    - name: Update apt cache on Debian-based systems
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Update dnf cache on RedHat-based systems
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts['os_family'] == "RedHat"

  tasks:
    - name: Register to Redhat.
      community.general.redhat_subscription:
        state: present
        org_id: "19047241"
        activationkey: "redhat10"
      when: ansible_distribution == "RedHat"

    - name: Install OpenSSH
      ansible.builtin.include_role:
        name: ansible-role-openssh

    - name: Install Python
      ansible.builtin.include_role:
        name: ansible-role-python

    - name: Add group for DevOps user
      ansible.builtin.group:
        name: developers
        state: present

    - name: Make DevOps user
      ansible.builtin.user:
        name: devops
        state: present
        shell: /bin/bash
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
        create_home: true
        groups:
          - "{{ (ansible_os_family == 'RedHat') | ternary('wheel', 'sudo') }}"
          - developers
        append: true

    - name: Allow the bob user to run any commands
      community.general.sudoers:
        name: devops
        state: present
        user: devops
        commands: ALL

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  post_tasks:
    - name: Test SSH connection as devops user
      ansible.builtin.command: whoami
      #become_user: devops
      register: whoami_output
      changed_when: false

    - name: Display whoami output
      ansible.builtin.debug:
        msg: "The current user is {{ whoami_output.stdout }}"
